version: '3'
services:
  photo-gallery-redis-blue:
    image: redis:latest
    container_name: photo-gallery-redis-blue
  photo-gallery-blue:
    image: georgesavill/photography-gallery:development-blue
    container_name: photo-gallery-blue
    volumes:
      - /home/george/photography-gallery/photos:/app/wwwroot/images
      - /mnt/dev-server-storage/photos:/tmp/photography-gallery-input-images
    ports:
      - 8180:80
    depends_on:
      - photo-gallery-redis-blue
    restart: always