version: '3'
services:
  photo-gallery-redis:
    image: redis:latest
    restart: always
  photo-gallery:
    image: georgesavill/photography-gallery:latest
    volumes:
      - /home/george/photography-gallery/photos:/app/wwwroot/images
      - /mnt/prod-server-storage/photos:/tmp/photography-gallery-input-images
    ports:
      - 8181:80
    depends_on:
      - photo-gallery-redis
    restart: always