version: '3'
services:
  photo-gallery:
    image: photo-gallery
    volumes:
      - /home/george/photography-gallery/photos:/app/wwwroot/images
      - /mnt/prod-server-storage/photos:/tmp/photography-gallery-input-images
    ports:
      - 8181:80
    restart: always